baseURL: https://www.docsacademy.net/
languageCode: en-us
title: Блог об эффективном создании контента
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/docsacademy.png
    link: /
    # Default width/height. Uncomment if you need to change
    # width: 112
    # height: 28
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Обучайся. Развивайся.
    # Hero subtitle (optional)
    subtitle: На этом сайте Вы найдете полезные ресурсы по эффективному созданию контента.
    # Button text
    buttontext: Начать
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: О сайте
    url: /
  - title: Обзор курсов
    url: /course-overview
  - title: Выбор курса
    sublinks:
    - title: Курс 1
      url: /course1
    - title: Курс 2
      url: /course2
    - title: Курс 3
      url: /course3
  # - title: Log in
  #  url: /
  # - title: Sign up
  #   url: /
  #  button: true
  sidebar:
    # Logo (from /images/logos/___.svg)
    logo: fresh-square
    sections:
    - title: Выбор курса
      icon: image
      links:
      - text: Курс 1
        url: /
      - text: Курс 2
        url: /
      - text: Курс 3
        url: /
  section1:
    title: Популярные курсы
    subtitle: бесплатно для Вас
    tiles:
    - title: Markdown и другие языки разметки
      icon: mouse-globe
      text: Научитесь работать с Markdown и не только
      url: /
      buttonText: Подробнее...
    - title: Генераторы статических сайтов
      icon: laptop-cloud
      text: Создайте безопасный сайт почти бесплатно
      url: /
      buttonText: Подробнее...
    - title: XML & DITA & техническая документация
      icon: plug-cloud
      text: Узнайте все о современных стандартах
      url: /
      buttonText: Подробнее...
  section2:
    title: Научитесь новому сегодня
    subtitle: А мы Вам поможем
    features:
    - title: Powerful and unified interface
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Cross-device synchronisation
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Nomad system
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  section4:
    title: Что думают пользователи о нас!
    subtitle: Узнайте, почему пользователи доверяют нам
    clients:
    - name: Василий Петров
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Начинающий техписатель
      img: 1
    - name: Анна Белая
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Студентка
      img: 2
    - name: Павел Дронников
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Менеджер
      img: 3
  section5: false