################################# Default configuration ###################
# provide your domain here
baseURL = "https://www.docsacademy.net/"
# theme
theme = "dot-hugo"
# site title
title = "DocsAcademy"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "G-HJ6VE57QCX"
# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "DocsAcademy"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# customize color
primary_color = "#02007e"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = "Copyright &copy; 2023 by DocsAcademy"

# banner
[Languages.en.params.banner]
title = "Courses for you"
subtitle = "Markdown, XML, DITA, SDL Trados Studio and more"
bg_image = "images/banner.jpg"
# placeholder = "Enter your term"


################## english navigation #################
[[Languages.en.menu.main]]
name = "Main"
url = ""
weight = 1

# Dropdown menu
[[Languages.en.menu.main]]
weight = 4
name = "Tutorials"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Tutorials"
  name = "DITA"
  url = "dita/"
  weight = 2